### ISSUE TITLE
API to share encrypted data with organization

### ISSUE THREAD

**Issue by gjermundgaraba** [empowerchain/deposit-backend#15]
We can put this new API under the organization service.

We need a new table for this data where each row is data shared by a user.
The primary key should be a composite key of the user pub key and the organization pub key (This is because only one share per user per organization to keep things simpler).

The API should take in the encrypted data and store it directly in the database.
The data is encrypted on the client side (in the app), so the API should be pretty simple.

Need a getter API as well for the organization to get the data for a user (and all data for a single organization).

**Comment by gfant** [comment]
Model of json to send to db
```
{
     organizaiton_pub_key : organizaiton_pub_key,
     user_pub_key : user_pub_key,
     data : info
}
```

info is encrypted using the **organization public key** and contains `name, lastName, mail, organizationId`
