### ISSUE TITLE
API to get organizations the user has interacted with

### ISSUE THREAD

**Issue by gjermundgaraba** [empowerchain/deposit-backend#16]
Create a new API endpoint under the deposit service to get all organizations the user has deposited to.

- [x] Write the new endpoint
- [x] Write tests for the new endpoint

It should return a list like this:
```json
{
  "depositOrgsForUser": [
    {
      "organizationId": "abc123",
      "organizationName": "Some org name",
    },
    {
       "organizationId": "def456",
       "organizationName": "Some other org name",
    }
  ]
}
```

**Comment by gfant** [comment]
This function was made in the stats service, under the name of `GetOrganizationsByUser`.
